# -*- coding: utf-8 -*-
"""Data_Cleaning-Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16S30KEs-OIEboaqDCfvp-ZZvTftYEHDk

# Data Cleaning in Python

Project: Airbnb Open Data – Data Cleaning and Preparation

Data Cleaning Steps:
1. Remove redundant and irrelevant columns
2. Standardize and rename column names
3. Identify and remove duplicate records
4. Clean and standardize individual column values
5. Handle missing values
6. Apply additional data transformations as needed

Dataset Source:
https://www.kaggle.com/datasets/arianazmoudeh/airbnbopendata
"

# 1. Insert Dataset
"""

import pandas as pd

# Meng Import dataset-csv
data = pd.read_csv("Airbnb_Open_Data.csv")

# Mengecek 5 data teratas
data.head(5)

# Menampilkan keseluruhan kolom
data.columns

# Menampilkan dimensi data
data.shape

# untuk mengecek informasi data
# membandingkan nilai yg tidak null terhadap yang null pada tiap kolom
data.info()

"""# a. Remove redundant and irrelevant columns"""

data.info()
# lihat pada bagian last_review (perbedaan datanya sangat besar dibandign sebelumnya)
# namun pada kasus ini kita drop dari review_per_month

data.columns

columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license','id']

# Menghitung jumlah kolom
len(columns_to_keep)

# Menghitung jumlah kolom
len(columns_to_drop)

"""1. Filtering Data (First Method) - (Buat variabel tiap kali mau edit dataset😡😡)"""

# menampilkan data sesuai variabel kolom
# tampilan hanya menampilkan query terakhir
data[columns_to_keep]
data[columns_to_drop]

dk = data[columns_to_keep]
dd = data[columns_to_drop]

# drop kolom
data_DC1 = data.drop(columns = ['license']) # cara ke-1
data_DC = data.drop(columns = dd) # drop dari variabel data_DC
data_DC.head(2) # total jadi 19 kolom
data_DC.shape # cek dimensi

"""2. Dropping Column (Second Method)- (Tanpa buat variabel tiap kali mau edit dataset😡😡)"""

data.head(1) # kolum di data masih full
data.columns

data.drop(columns = dd,inplace = True) # drop langsung ke data aslinya, tanpa buat variabel baru
data # data asli yg udah di drop

# Note: kl udah di drop gak bisa di drop lagi (Error)

"""# b. Standardize and rename column names"""

# dalam merename column, menggunakan dictionary
data.columns

# merename kolom NAME
data.rename(columns = {"NAME":"Name"})
data.rename(columns = {"NAME":"Name"}, inplace = True) # mengubah data utama
data.head(2) # sudah keubah

for i in data.columns:
  print(i.upper()) # buat semua kolom kapital

for i in data.columns:
  print(i.lower ()) # buat semua lower

New_CN_L = [] # untuk menampung list kolom baru (Kecil)
for i in data.columns:
 New_CN_L.append(i.lower ()) # buat semua lower

New_CN_L # menampilkan semua kolom lower

data_cl = data.copy() # copy dari data utama, untuk coba ganti kolom ke lower

data_cl.columns = New_CN_L # ubah kolom yg awalnya H.bsar jadi kecil

data_cl.head(2) # nama kolom udah kecil semua

"""# c. Identify and remove duplicate records"""

data.duplicated() # kl duplicate True
data.duplicated().sum() # menghitung jumlah Duplicate True
data.duplicated().value_counts() # menghitung jumlah Duplicate True dan False

# clean_data = data.drop_duplicates() # buat variabel
# atau
# aku pilh yg bawah
data.drop_duplicates(inplace = True) # langsung ganti ke data utama

data.duplicated().value_counts() # udah gak ada data duplicate

ss

"""# d. Clean and standardize individual column values"""

data.isna().sum() # last review merupakan kolom dengan NA terbanyak

data.drop(columns = "last review" )

# data_no_NA = data bersih tanpa NA
data_no_NA = data.dropna()

# ngecek lagi
data_no_NA.isna().sum() # udah gak ada data yang NA

"""# e. Handle missing values from the dataset

1. Mengubah host_identity_verified jadi UPPER
"""

# dari sini pake variabel data_no_NA
data_no_NA['host_identity_verified']

# Mengubah hasil host_identity_verified jadi uppercase
data_no_NA['host_identity_verified'].str.upper()

data_no_NA.head(2) # belum berubah

# cara mengubah hasilnya di data_no_NA
data_no_NA['host_identity_verified'] = data_no_NA['host_identity_verified'].str.upper()

data_no_NA.head(2) # udah berubah hasil di 'host_identity_verified'

"""2. Mengubah instant_bookable jadi bolean (0 atau 1)"""

data_no_NA ['instant_bookable'].apply(lambda x: 1 if x == True else 0)

data_no_NA.head(2)

data_no_NA ['instant_bookable'] = data_no_NA ['instant_bookable'].apply(lambda x: 1 if x == True else 0) # df(kolom) = df(kolom).method()

data_no_NA.head(5) # udah keubah (Done)

"""# f. Check for some more transformation

**1. Cek index atau penomerannya udah bener belum**
"""

data_no_NA['instant_bookable'][5] # ada nilainya satu

data_no_NA['instant_bookable'][15] # ini error gak ada nilainya

# cek data
data_no_NA.head(5) # nomor data lompat2

#solusi reset index
data_no_NA.reset_index(inplace = True)

# cek lagi
data_no_NA.head(5) # index yang benar udah muncul

# Terakhir coba lagi yg data no 15
data_no_NA['instant_bookable'][15] # udah gak error

"""**2. Ganti mata uang yg awalnya string jadi int dan menghilangkan spaci berlebih**

a. Data Cleaning
"""

data_no_NA.head(3) # pada price masih ada $, spasi berlebih, sama koma

type (data_no_NA['price'][2]) # data type masih string

data_no_NA.info() # dtype object- belum tentu string, bisa jadi campuran int, string, float, dll (cek lagi)

data_no_NA['price'].head(10) # buat cek jenis datanya dari perhitungan di bawah 🤑🤑
# 1. Dolar udah ilang

# 1. menghilangkan dolar
from numpy._core.defchararray import replace
data_no_NA ['price'] = data_no_NA['price'].str.replace('$','')

# 2. menghilangkang koma
data_no_NA ['price'] = data_no_NA['price'].str.replace(',','')

# 2. menghilangkang koma
data_no_NA ['price'] = data_no_NA['price'].str.replace(',','')

# 3. menghilangkang spasi gak jelas
data_no_NA ['price'] = data_no_NA['price'].str.replace(' ','')

"""b. Ganti mata uang menjadi string"""

# mengganti data type
data_no_NA['price'] = data_no_NA['price'].astype(int)

# mengecek kembali
type (data_no_NA['price'][100])
type (data_no_NA['price'][5]) # udah bener integer

"""# Ekspor file yang udah di Cleaning

"""

# ekspor data dari dataframe ke CSV
data_no_NA.to_csv('Cleaned_Data.csv')

# baca di python
pd.read_csv('Cleaned_Data.csv')

"""#"""